### ISSUE TITLE
training_page_id parameter does not work

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboardTools#1]
No matter what I put for training ID, the endpoint always reports me as trained: http://tools.wmflabs.org/wikiedudashboard/users.php?user_ids[0]=319203&user_ids[1]=678910&training_page_id=99999999999999

**Comment by ragesoss** [comment]
@ntdb did you deploy the latest version of this on wmflabs?

@thenickcox we need to get you set up as a maintainer of this tool on wmflabs.org, when we get a chance. Not urgent, though.

**Comment by ntdb** [comment]
@ragesoss I don't believe I did, actually.
