### ISSUE TITLE
Does not return results for Wikidata

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboardTools#7]
I think it doesn't handle the lack of a language prefix for the wikidata database in common.php.

Fixing this would, I think, let us enable wikidata on the Programs & Events Dashboard.

cc @Ladsgroup

**Comment by Ladsgroup** [comment]
Would #8 solve it?

**Comment by ragesoss** [comment]
Yep! That did it. It'll take some more work to get it sorted out fully on the dashboard, but this should make it possible.

Live and working: http://tools.wmflabs.org/wikiedudashboard/revisions.php?lang=www&project=wikidata&usernames[]=Ragesoss&oauth_tags[]=%27OAuth+CID%3A+542%27&start=20160310&end=20161201
